Update release_multiple.yml

diff --git a/.github/workflows/release_multiple.yml b/.github/workflows/release_multiple.yml
--- a/.github/workflows/release_multiple.yml
+++ b/.github/workflows/release_multiple.yml
@@ -66,7 +66,7 @@ jobs:
     steps:
       - name: print
         run: |
-          valores=($(echo "${{ needs.get_list_matrix_fail.outputs.matrix_status}}" | sed -n 's/[^)]*)/(&\n)/g;p' | grep -oP '\(\K[^)]*(?=\))') || true)
+          valores=($(echo "${{ needs.get_list_matrix_fail.outputs.matrix_status}}" | sed -n 's/[^)]*)/(&\n)/g;p' | grep -oP '\(\K[^)]*(?=\))' || true))
           echo "${valores[@]}"
           echo ${{ needs.get_list_matrix_fail.outputs.matrix_status}}
 
